package com.gecesars.atxplan.data.antenna

import com.gecesars.atxplan.domain.antenna.AntennaPatternCut
import com.gecesars.atxplan.domain.antenna.CanonicalAntennaPattern
import com.gecesars.atxplan.domain.antenna.PatternCoordinateFrame
import com.gecesars.atxplan.domain.antenna.PatternCutAvailability
import com.gecesars.atxplan.domain.antenna.PatternCutPlane
import com.gecesars.atxplan.domain.antenna.PatternOrigin
import com.gecesars.atxplan.domain.antenna.PatternProvenance
import com.gecesars.atxplan.domain.antenna.PatternSample
import com.gecesars.atxplan.ui.antenna.AntennaPatternExportFormat
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import kotlin.math.cos
import kotlin.math.max

class AntennaPatternDesktopTableParityTest {
    @Test
    fun `desktop V-Soft HRP fixture imports exactly 360 magnitudes without a companion cut`() {
        val values = (0 until 360).map { angle ->
            0.25 + 0.75 * max(cos(Math.toRadians(angle.toDouble())), 0.0)
        }
        val payload = buildString {
            appendLine("360,0,1")
            values.forEach { value -> appendLine("%.4f".format(java.util.Locale.US, value)) }
        }.toByteArray()

        val decoded = AntennaPatternFileCodecs.decode(payload, "desktop_hrp.vep")

        assertEquals(AntennaPatternFileFormat.VSOFT_HRP, decoded.detectedFormat)
        assertNull(decoded.pattern)
        assertEquals(PatternCutPlane.HORIZONTAL, decoded.cuts.single().plane)
        assertEquals(360, decoded.cuts.single().samples.size)
        assertEquals((0 until 360).map(Int::toDouble), decoded.cuts.single().samples.map { it.angleDegrees })
        assertTrue(decoded.cuts.single().samples.all { sample -> sample.phaseDegrees == null })
        assertNull(decoded.metadata.nominalFrequencyHz)

        val completed = AntennaPatternCodec.parse(payload, "desktop_hrp.vep")
        assertTrue(completed.warnings.any { warning -> warning.contains("V-Soft HRP file") })
        assertTrue(completed.warnings.any { warning -> warning.contains("not measured or calculated data") })
        assertTrue(
            completed.pattern.verticalCut.samples.all { sample ->
                sample.normalizedFieldAmplitude == 1.0
            },
        )
    }

    @Test
    fun `V-Soft exports match desktop headers grids tilt and four-decimal magnitude contract`() {
        val source = referencePattern()

        val horizontal = AntennaPatternFileCodecs.encodeVSoft(source.horizontalCut)
        val horizontalLines = horizontal.payload.toString(Charsets.UTF_8).lines().dropLast(1)
        assertEquals(AntennaPatternFileFormat.VSOFT_HRP, horizontal.format)
        assertEquals("360,0,1", horizontalLines.first())
        assertEquals(361, horizontalLines.size)
        assertTrue(horizontalLines.drop(1).all { value -> value.matches(Regex("\\d\\.\\d{4}")) })
        assertTrue(horizontal.warnings.any { warning -> warning.contains("cannot represent phase") })

        val vertical = AntennaPatternFileCodecs.encodeVSoft(source.verticalCut)
        val verticalLines = vertical.payload.toString(Charsets.UTF_8).lines().dropLast(1)
        assertEquals(AntennaPatternFileFormat.VSOFT_VRP, vertical.format)
        assertEquals(
            "Generated by EFTX ADT Elevation Pattern for use in V-Soft software",
            verticalLines[0],
        )
        assertEquals("Beam Tilt = 0.0", verticalLines[1])
        assertEquals(1803, verticalLines.size)
        assertEquals(-90.0, verticalLines[2].trim().substringBefore(' ').toDouble(), STRICT_TOLERANCE)
        assertEquals(90.0, verticalLines.last().trim().substringBefore(' ').toDouble(), STRICT_TOLERANCE)

        val decoded = AntennaPatternFileCodecs.decode(vertical.payload, "roundtrip_vrp.vep")
        assertEquals(AntennaPatternFileFormat.VSOFT_VRP, decoded.detectedFormat)
        assertEquals(0.0, decoded.metadata.beamTiltDegrees!!, STRICT_TOLERANCE)
        assertEquals(1801, decoded.cuts.single().samples.size)
        assertEquals(1.0, decoded.cuts.single().complexFieldAt(0.0).magnitude, ROUND_TRIP_TOLERANCE)
        assertEquals(0.1, decoded.cuts.single().complexFieldAt(-90.0).magnitude, ROUND_TRIP_TOLERANCE)
    }

    @Test
    fun `desktop generic HRP CSV chooses varying theta ignores info columns and preserves GHz metadata`() {
        val payload = """
            "Freq [GHz]","Phi [deg]","Theta [deg]","10^(dB10normalize(GainL3y)/20) []"
            0.471,90,-180,0.765423809360821
            0.471,90,-179,0.765369844098952
            0.471,90,-178,0.765240321126155
            0.471,90,0,1.000000000000000
            0.471,90,1,0.999500000000000
            0.471,90,179,0.765369844098952
        """.trimIndent().plus("\n").toByteArray()

        val decoded = AntennaPatternFileCodecs.decode(payload, "azimuth_hpol.csv")

        assertEquals(AntennaPatternFileFormat.GENERIC_HRP_TABLE, decoded.detectedFormat)
        assertEquals(
            AntennaPatternValueConvention.NORMALIZED_FIELD_AMPLITUDE,
            decoded.valueConvention,
        )
        assertEquals(471.0e6, decoded.metadata.nominalFrequencyHz!!, STRICT_TOLERANCE)
        val cut = decoded.cuts.single()
        assertEquals(360, cut.samples.size)
        assertEquals(1.0, cut.complexFieldAt(0.0).magnitude, STRICT_TOLERANCE)
        assertTrue(cut.samples.all { sample -> sample.phaseDegrees == null })
    }

    @Test
    fun `desktop generic VRP dB CSV converts relative field dB and resamples point one degree grid`() {
        val payload = """
            "Freq [GHz]","Phi [deg]","Theta [deg]","dB10normalize(GainL3X) []"
            0.186,90,-2,-0.0118115213671719
            0.186,90,-1,-0.00218568255865022
            0.186,90,0,0
            0.186,90,1,-0.00525649721008869
            0.186,90,2,-0.0179427147779443
        """.trimIndent().plus("\n").toByteArray()

        val decoded = AntennaPatternFileCodecs.decode(payload, "elevation_vrp.csv")

        assertEquals(AntennaPatternFileFormat.GENERIC_VRP_TABLE, decoded.detectedFormat)
        assertEquals(AntennaPatternValueConvention.RELATIVE_FIELD_DB_20_LOG10, decoded.valueConvention)
        assertEquals(186.0e6, decoded.metadata.nominalFrequencyHz!!, STRICT_TOLERANCE)
        val cut = decoded.cuts.single()
        assertEquals(1801, cut.samples.size)
        assertEquals(-90.0, cut.samples.first().angleDegrees, STRICT_TOLERANCE)
        assertEquals(90.0, cut.samples.last().angleDegrees, STRICT_TOLERANCE)
        assertEquals(1.0, cut.complexFieldAt(0.0).magnitude, STRICT_TOLERANCE)
        assertTrue(cut.complexFieldAt(-1.0).magnitude < 1.0)
        assertTrue(cut.complexFieldAt(1.0).magnitude < 1.0)
    }

    @Test
    fun `desktop text-table headers can declare plane and nominal MHz without a plane suffix`() {
        val payload = """
            manufacturer: EFTX
            pattern_plane: Elevation
            frequency_MHz: 99.50
            E / Emax (voltage)
            Angle Magnitude
            -90 0.1
            0 1.0
            90 0.1
        """.trimIndent().plus("\n").toByteArray()

        val decoded = AntennaPatternFileCodecs.decode(payload, "desktop-export.txt")

        assertEquals(AntennaPatternFileFormat.GENERIC_VRP_TABLE, decoded.detectedFormat)
        assertEquals(99.5e6, decoded.metadata.nominalFrequencyHz!!, STRICT_TOLERANCE)
        assertEquals(1801, decoded.cuts.single().samples.size)
    }

    @Test
    fun `explicit generic phase column is preserved through complex interpolation`() {
        val payload = """
            angle,magnitude,phase
            0,1.0,0
            90,0.8,90
            180,0.4,180
            270,0.8,-90
        """.trimIndent().plus("\n").toByteArray()

        val decoded = AntennaPatternFileCodecs.decode(payload, "measured.hrp")

        assertEquals(AntennaPatternFileFormat.GENERIC_HRP_TABLE, decoded.detectedFormat)
        assertEquals(
            AntennaPatternValueConvention.NORMALIZED_FIELD_AMPLITUDE_WITH_OPTIONAL_PHASE,
            decoded.valueConvention,
        )
        val sample = decoded.cuts.single().samples.single { row -> row.angleDegrees == 90.0 }
        assertEquals(0.8, sample.normalizedFieldAmplitude, STRICT_TOLERANCE)
        assertEquals(90.0, sample.phaseDegrees!!, STRICT_TOLERANCE)
    }

    @Test
    fun `ambiguous conflicting and geospatial tables fail closed`() {
        val ambiguous = """
            angle,magnitude
            0,1.0
            90,0.5
            180,0.2
        """.trimIndent().toByteArray()
        expectCodecFailure {
            AntennaPatternFileCodecs.decode(ambiguous, "ambiguous.csv")
        }.also { error -> assertTrue(error.message.orEmpty().contains("ambiguous")) }

        val conflicting = """
            pattern_plane: Elevation
            angle,magnitude
            0,1.0
            90,0.5
            180,0.2
        """.trimIndent().toByteArray()
        expectCodecFailure {
            AntennaPatternFileCodecs.decode(conflicting, "conflict.hrp")
        }.also { error -> assertTrue(error.message.orEmpty().contains("conflict")) }

        expectCodecFailure {
            AntennaPatternFileCodecs.decode(
                "<kml><coordinates>0,1 90,0.5 180,0.2</coordinates></kml>".toByteArray(),
                "antenna.kml",
            )
        }.also { error -> assertTrue(error.message.orEmpty().contains("KML and KMZ")) }

        expectCodecFailure {
            AntennaPatternFileCodecs.decode(
                byteArrayOf(0x50, 0x4b, 0x03, 0x04),
                "antenna.kmz",
            )
        }.also { error -> assertTrue(error.message.orEmpty().contains("KML and KMZ")) }
    }

    @Test
    fun `facade exports both V-Soft UI formats and generic formats remain import only`() {
        val source = referencePattern()

        val horizontal = AntennaPatternCodec.encode(source, AntennaPatternFileFormat.VSOFT_HRP)
        val vertical = AntennaPatternCodec.encode(source, AntennaPatternFileFormat.VSOFT_VRP)

        assertTrue(horizontal.toString(Charsets.UTF_8).startsWith("360,0,1\n"))
        assertTrue(vertical.toString(Charsets.UTF_8).startsWith("Generated by EFTX ADT Elevation"))
        assertEquals("vep", AntennaPatternExportFormat.VSOFT_HRP.extension)
        assertEquals("vep", AntennaPatternExportFormat.VSOFT_VRP.extension)
        expectCodecFailure {
            AntennaPatternCodec.encode(source, AntennaPatternFileFormat.GENERIC_HRP_TABLE)
        }.also { error -> assertTrue(error.message.orEmpty().contains("import-only")) }
    }

    private fun referencePattern(): CanonicalAntennaPattern {
        val provenance = PatternProvenance(
            origin = PatternOrigin.IMPORTED,
            sourceLabel = "Desktop parity fixture",
            sourceFormat = "Controlled fixture",
            sourceSha256 = "b".repeat(64),
            coordinateFrame = PatternCoordinateFrame.APERTURE_XY_BORESIGHT_Z,
            sourceCoordinateFrame = PatternCoordinateFrame.SOURCE_RELATIVE_UNSPECIFIED,
            engineId = "desktop-parity-test-v1",
        )
        return CanonicalAntennaPattern(
            id = "desktop-parity",
            name = "Desktop parity",
            horizontalCut = AntennaPatternCut(
                PatternCutPlane.HORIZONTAL,
                listOf(
                    PatternSample(0.0, 1.0, 0.0),
                    PatternSample(90.0, 0.5, 30.0),
                    PatternSample(180.0, 0.25, 0.0),
                    PatternSample(270.0, 0.5, -30.0),
                ),
                provenance,
                PatternCutAvailability.AVAILABLE,
            ),
            verticalCut = AntennaPatternCut(
                PatternCutPlane.VERTICAL,
                listOf(
                    PatternSample(-90.0, 0.1, 0.0),
                    PatternSample(0.0, 1.0, 0.0),
                    PatternSample(90.0, 0.1, 0.0),
                ),
                provenance,
                PatternCutAvailability.AVAILABLE,
            ),
            provenance = provenance,
            nominalFrequencyHz = 100.1e6,
        )
    }

    private fun expectCodecFailure(block: () -> Unit): AntennaPatternCodecException {
        try {
            block()
        } catch (error: AntennaPatternCodecException) {
            return error
        }
        throw AssertionError("Expected AntennaPatternCodecException.")
    }

    private companion object {
        const val STRICT_TOLERANCE = 1.0e-9
        const val ROUND_TRIP_TOLERANCE = 1.0e-4
    }
}
